version: '3.4'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: BlogDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Strong!P4ssw0rd
    ports:
      - "5432:5432"

  blogapi:
    image: blogapi
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      ConnectionStrings__PostgresDev: "Host=postgres;Port=5432;Database=BlogDb;Username=postgres;Password=Strong!P4ssw0rd"
    ports:
      - "5000:8080"